# Generated by Django 4.2.1 on 2023-06-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2021-02-02'),
            preserve_default=False,
        ),
    ]
